# Generated by Django 4.0.6 on 2022-07-29 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_status', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=50, verbose_name='Aktiflik Durumu')),
                ('name', models.CharField(max_length=200, verbose_name='İş')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_status', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=50, verbose_name='Aktiflik Durumu')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='İş Açıklaması')),
                ('job_post_status', models.CharField(blank=True, choices=[('Tamamlandı', 'Tamamlandı'), ('İptal Oldu', 'İptal Oldu')], max_length=50, null=True, verbose_name='İş Durumu')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İş Veren')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job', verbose_name='İş')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_status', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=50, verbose_name='Aktiflik Durumu')),
                ('jobseeker_note', models.TextField(blank=True, null=True, verbose_name='Başvuru Notu')),
                ('employer_note', models.TextField(blank=True, null=True, verbose_name='İnceleme Notu')),
                ('job_application_status', models.CharField(blank=True, choices=[('Onaylandı', 'Onaylandı'), ('Reddedildi', 'Reddedildi'), ('İnceleniyor', 'İnceleniyor'), ('Bekleniyor', 'Bekleniyor')], max_length=60, null=True, verbose_name='Başvuru Durumu')),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jobpost', verbose_name='İş İlanı')),
                ('jobseeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İşe Başvuran')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
