# Generated by Django 4.0.6 on 2022-07-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_status', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive')], default='Active', max_length=50, verbose_name='Aktiflik Durumu')),
                ('name', models.CharField(max_length=255, verbose_name='Şehir')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='working_model',
            field=models.CharField(blank=True, choices=[('Uzaktan', 'Uzaktan'), ('Hybrid', 'Hybrid'), ('Yerinde', 'Yerinde')], max_length=50, null=True, verbose_name='Çalışma Modeli'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job',
            field=models.CharField(max_length=255, verbose_name='İş Başlığı'),
        ),
    ]
