# Generated by Django 4.0.6 on 2022-07-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_careerprofile_targeted_jobs_and_more'),
        ('core', '0002_province_jobpost_working_model_alter_jobpost_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province', verbose_name='Çalışma Modeli'),
        ),
    ]
