# Generated by Django 4.0.6 on 2022-07-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_job_jobpost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_post_status',
            field=models.CharField(blank=True, choices=[('Tamamlandı', 'Tamamlandı'), ('İptal Oldu', 'İptal Oldu'), ('İlan Sürecinde', 'İlan Sürecinde')], default='İlan Sürecinde', max_length=50, null=True, verbose_name='İş Durumu'),
        ),
    ]
