# Generated by Django 4.0.6 on 2022-07-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobapplication_uuid_jobpost_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
