# Generated by Django 4.0.6 on 2022-07-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_jobapplication_uuid_alter_jobpost_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_required',
            field=models.TextField(blank=True, null=True, verbose_name='Aranan Nitelikler'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job',
            field=models.CharField(max_length=255, verbose_name='Pozisyon'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='İş Tanımı'),
        ),
    ]
