# Generated by Django 4.0.6 on 2022-07-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_province_jobpost_working_model_alter_jobpost_job'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerprofile',
            name='targeted_jobs',
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='location',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province', verbose_name='Çalışma Modeli'),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='target_job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='İş Başlığı'),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='working_model',
            field=models.CharField(blank=True, choices=[('Uzaktan', 'Uzaktan'), ('Hybrid', 'Hybrid'), ('Yerinde', 'Yerinde')], max_length=50, null=True, verbose_name='Çalışma Modeli'),
        ),
    ]
