# Generated by Django 4.0.6 on 2022-07-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_careerprofile_targeted_jobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerprofile',
            name='target_job_title',
        ),
    ]
