# Generated by Django 4.0.6 on 2022-07-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobapplication_uuid_jobpost_uuid_and_more'),
        ('user', '0003_remove_careerprofile_target_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerprofile',
            name='location',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province', verbose_name='Konum'),
        ),
    ]
