# Generated by Django 4.0.6 on 2022-07-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_careerprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerprofile',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pozisyon'),
        ),
    ]
